"""
Pydantic schemas for the inflammation endpoint.

Two distinct meanings of "status" live side by side here, deliberately kept
apart rather than collapsed into one field:
  - InflammationStatus ("calibrating" | "scored") answers "do we have enough
    history to say anything at all?" — this is score.ts/inflammation_scoring's
    own vocabulary.
  - status_label ("low" | "moderate" | "high") is the schema's human-facing
    severity bucket (firewatch-schema.mermaid's INFLAMMATION_SCORES.status
    comment), only meaningful once status == scored.
"""

from datetime import date, datetime
from enum import Enum

from pydantic import BaseModel


class InflammationStatus(str, Enum):
    calibrating = "calibrating"
    scored = "scored"


class InflammationResponse(BaseModel):
    user_id: str
    date: date
    status: InflammationStatus

    # Populated only when status == scored.
    score: float | None = None  # continuous severity from inflammation_scoring.score_series
    level: int | None = None  # 1-5
    status_label: str | None = None  # "low" | "moderate" | "high" — see module docstring
    insight_text: str | None = None  # LLM-generated, cached; not generated by this endpoint

    # Populated only when status == calibrating, so the client can show
    # progress ("18 days to go") instead of a bare "not ready" message.
    days_of_history: int
    days_until_scored: int | None = None

    computed_at: datetime | None = None

    class Config:
        from_attributes = True